services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    networks:
      - ecommerce-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    container_name: redis_cache
    networks:
      - ecommerce-network
    restart: always
    ports:
      - "6379:6379"

  django:
    build: ./django_app
    container_name: django_backend
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    networks:
      - ecommerce-network
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/app
    command: python manage.py runserver 0.0.0.0:8000

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
