# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckStock = channel.unary_unary(
                '/product.ProductService/CheckStock',
                request_serializer=product__pb2.ProductRequest.SerializeToString,
                response_deserializer=product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/product.ProductService/GetProduct',
                request_serializer=product__pb2.ProductIdRequest.SerializeToString,
                response_deserializer=product__pb2.ProductDetailResponse.FromString,
                _registered_method=True)
        self.ReduceStock = channel.unary_unary(
                '/product.ProductService/ReduceStock',
                request_serializer=product__pb2.ReduceStockRequest.SerializeToString,
                response_deserializer=product__pb2.ReduceStockResponse.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckStock(self, request, context):
        """
        Checks the availability of stock for a given product.
        Accepts a ProductRequest containing product details and returns a ProductResponse
        indicating the stock status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """
        Retrieves detailed information about a specific product.
        Accepts a ProductIdRequest containing the product ID and returns a ProductDetailResponse
        with comprehensive product details.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReduceStock(self, request, context):
        """
        Reduces the stock quantity for a list of products.

        This RPC method accepts a `ReduceStockRequest` containing a list of product IDs 
        and their respective quantities to reduce. It returns a `ReduceStockResponse` 
        indicating whether the operation was successful or not.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=product__pb2.ProductRequest.FromString,
                    response_serializer=product__pb2.ProductResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=product__pb2.ProductIdRequest.FromString,
                    response_serializer=product__pb2.ProductDetailResponse.SerializeToString,
            ),
            'ReduceStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReduceStock,
                    request_deserializer=product__pb2.ReduceStockRequest.FromString,
                    response_serializer=product__pb2.ReduceStockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/CheckStock',
            product__pb2.ProductRequest.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetProduct',
            product__pb2.ProductIdRequest.SerializeToString,
            product__pb2.ProductDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReduceStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ReduceStock',
            product__pb2.ReduceStockRequest.SerializeToString,
            product__pb2.ReduceStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
