# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x0fProductResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\r\n\x05price\x18\x02 \x01(\x02\x32Q\n\x0eProductService\x12?\n\nCheckStock\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=26
  _globals['_PRODUCTREQUEST']._serialized_end=54
  _globals['_PRODUCTRESPONSE']._serialized_start=56
  _globals['_PRODUCTRESPONSE']._serialized_end=107
  _globals['_PRODUCTSERVICE']._serialized_start=109
  _globals['_PRODUCTSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
